version: '3'


services:
  db:
    image: postgress:14.4
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSGRES_PASSWORD: ${DB_PASSWORD}
      POSGRES_DB: ${DB_NAME}
    container_name: anylistDB
    volumes:
      - ./postgres:/var/lib/postgresql/data